name: finea_academie
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.7
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0
  
  # Animation packages pour l'onboarding moderne
  animate_do: ^3.3.4
  smooth_page_indicator: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.1.2
  
  # Shared preferences pour sauvegarder l'état de l'onboarding
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
